##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot: 'Franka Hand'
collision_spheres:
    franka_hand:
        - "center": [0.0, -0.075, 0.01]
          "radius": 0.03
        - "center": [0.0, -0.045, 0.01]
          "radius": 0.03
        - "center": [0.0, -0.015, 0.01]
          "radius": 0.03
        - "center": [0.0, 0.015, 0.01]
          "radius": 0.03
        - "center": [0.0, 0.045, 0.01]
          "radius": 0.03
        - "center": [0.0, 0.075, 0.01]
          "radius": 0.03
        - "center": [0.0, 0.065, -0.02]
          "radius": 0.03
        - "center": [0.0, -0.075, 0.03]
          "radius": 0.03
        - "center": [0.0, -0.045, 0.03]
          "radius": 0.03
        - "center": [0.0, -0.015, 0.03]
          "radius": 0.03
        - "center": [0.0, 0.015, 0.03]
          "radius": 0.03
        - "center": [0.0, 0.045, 0.03]
          "radius": 0.03
        - "center": [0.0, 0.075, 0.03]
          "radius": 0.03
        - "center": [0.0, -0.075, 0.05]
          "radius": 0.02
        - "center": [0.0, -0.045, 0.05]
          "radius": 0.02
        - "center": [0.0, -0.015, 0.05]
          "radius": 0.02
        - "center": [0.0, 0.015, 0.05]
          "radius": 0.02
        - "center": [0.0, 0.045, 0.05]
          "radius": 0.02
        - "center": [0.0, 0.075, 0.05]
          "radius": 0.02
    franka_leftfinger:
        - "center": [0.0, 0.01, 0.04]
          "radius": 0.01
        - "center": [0.0, 0.01, 0.014]
          "radius": 0.01
    franka_rightfinger:
        - "center": [0.0, 0.01, 0.04]
          "radius": 0.01
        - "center": [0.0, 0.01, 0.014]
          "radius": 0.01